# Generated by Django 4.1.6 on 2023-02-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_storecategory_pub_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="purchase", name="total_price",),
    ]
