# Generated by Django 4.1.6 on 2023-02-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_remove_purchase_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owners",
                to="polls.storeowner",
            ),
        ),
        migrations.AlterField(
            model_name="storeowner",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="customers/avatars/"
            ),
        ),
    ]
