# Generated by Django 4.1.6 on 2023-02-26 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_store_owner_alter_storeowner_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mybug",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers_MYBAG",
                related_query_name="customers_MYBAG",
                to="polls.customer",
            ),
        ),
    ]
